/* --------------------------------------------------------------------
                         Skeleton Header File
                              Chapter 2

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define CLR_BLACK  (-1L)
#define ID_APPNAME   1

#define IDM_ABOUT  100
