{*******************************************************}
{                                                       }
{       "Hello, World" example program                  }
{                                                       }
{       Copyright (C) 1996    T M T   Corporation       }
{                                                       }
{*******************************************************}

program hello;
uses crt;
begin
    textcolor (lightred);
    writeln ('Hello, world');
end.
